apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: temp-service-template
  namespace: tenant-ns
spec:
  entrypoint: run-temp-service
  templates:
    - name: run-temp-service
      steps:
        - - name: run-temp-service
            templateRef:
              name: temp-service-template
              template: run-temp-service
              clusterScope: true
