apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: temp-service-
  namespace: tenant-ns
spec:
  entrypoint: run-temp-service
  workflowTemplateRef:
    name: temp-service-template
    clusterScope: true
